services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: newsposter
      POSTGRES_PASSWORD: newsposter
      POSTGRES_DB: newsposter
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
